collection:
    resource: "@CollectionBundle/Controller/"
    type:     annotation
    prefix:   /

sowp_api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api/v1

sowp_news:
    resource: "@NewsModuleBundle/Controller/"
    type: annotation
    prefix:   /

sowp_search:
    resource: "@SearchModuleBundle/Controller"
    type: annotation

sowp_dashboard:
    resource: "@SowpDashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

sowp_article:
    resource: "@SowpArticleBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: "/profile"

#fos_user_registration:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: "/register"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/resetting"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/profile"
