# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    sowp_news_module_upload_path: "%kernel.root_dir%/../web/upload/news_attachments"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

#  gedmo.listener.softdeleteable:
#    class: Gedmo\SoftDeleteable\SoftDeleteableListener
#    tags:
#        - { name: doctrine.event_subscriber, connection: default }
#    calls:
#        - [ setAnnotationReader, [ @annotation_reader ] ]
    news_module.attachment_upload:
        class: Sowp\NewsBundle\EventListener\Doctrine\AttachmentUploadListener
        arguments: [ '%sowp_news_module_upload_path%' ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    news_module.form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: ['@exercise_html_purifier.default']
    news_module.form.type.purified_textarea:
        class: Sowp\NewsBundle\Form\TinyMceType
        arguments: ['@news_module.form.transformer.html_purifier']
        tags:
            - { name: form.type }